# sudo docker compose up --build
version: '3.1'
services:

  # to connect to db execute:
  #   sudo docker exec -it -u postgres test_task-postgres-1 psql
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "55432:5432"
  
  PSTelegram:
    image: docker-pstelegram
    build: PSTelegram/
    depends_on:
      - PSDB
    ports:
      - "50001:8080"

  PSDB:
    image: docker-psdb
    build: PSBD/
    depends_on: 
    - postgres
    ports:
      - "50000:8080"