version: '3.9'
services:

  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "55432:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data

  PSTelegram:
    image: docker-pstelegram
    build: PSTelegram/
    environment:
      TZ: "Europe/Moscow"
    depends_on:
      - PSDB
    ports:
      - "50001:8080"

  PSDB:
    image: docker-psdb
    build: PSDB/
    depends_on: 
    - postgres
    ports:
      - "50000:8080"